# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://PiKa-9.github.io',
                'git_url': 'https://github.com/PiKa-9/miniai',
                'lib_path': 'miniai'},
  'syms': {'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')}}}
